import Head from "next/head";
import Image from "next/image";
import AboutUs from "../components/AboutUs";
import Contact from "../components/Contact";
import Hero from "../components/Hero";
import Products from "../components/Products";
import Projects from "../components/Projects";
import Services from "../components/Services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jason Agri Exports (PVT) Limited | Your Supply. Our Responsibility.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <AboutUs />
        <Products />
        <Projects />
        <Services />
        <Contact />
      </main>
    </>
  );
}
