import Head from "next/head";
import Image from "next/image";
import AboutUs from "../components/AboutUs";
import Contact from "../components/Contact";
import Hero from "../components/Hero";
import Products from "../components/Products";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Jason Agri Exports (PVT) Limited | Your Supply. Our Responsibility.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <AboutUs />
        <Products products={products} />
        <Contact />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const query = encodeURIComponent('*[ _type == "product" ]');
  const url = `${process.env.SANITY_URL}/v2021-10-21/data/query/production?query=${query}`;

  const results = await fetch(url).then((res) => res.json());

  if (!results.result || !results.result.length) {
    return {
      props: {
        products: [],
      },
    };
  } else {
    return {
      props: {
        products: results.result,
      },
    };
  }
}
